FROM joomla:3.9.18-php7.4

# Install Xdebug
RUN pecl install -f xdebug && docker-php-ext-enable xdebug
#RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;
