FROM joomla:5.1.0-php8.1-apache

# Install Xdebug
#RUN pecl install -f xdebug && docker-php-ext-enable xdebug
#RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;

#clean joomla isntallation
#RUN rm -rf /var/www/html/*
