version: '3.5'

services:

  # Our application to debug
  app:
    container_name: tuto-xdebug
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - '80:80'
    volumes:
        - './index.php:/var/www/html/index.php'
        - './test.php:/var/www/html/test.php'
        - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    # expose:
    #   - 9000
    # # environment:
    #   XDEBUG_CONFIG: client_host=host.docker.internal remote_port=9000 mode=1