version: '3.8'

networks:
  data: {}

services:
  joomla:
    #image: joomla:3.9.18-php7.4
    build:
      context: /home/joffroy/vhost/j4dev/ASGLM_Test/
      dockerfile: ./dockerfile
    restart: "no"
    links:
      - joomladb:mysql
    ports:
      - 9081:80
    volumes:
      - /home/joffroy/vhost/j4dev/ASGLM_Test/uploads.ini:/usr/local/etc/php/conf.d/upload-limit.ini
      - /home/joffroy/vhost/j4dev/ASGLM_Test/www:/var/www/html:rw
      # - /home/joffroy/vhost/j4dev/ASGLM_Test/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - /home/joffroy/vhost/j4dev/ASGLM_Test/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    networks:
      - data

  joomladb:
    image: mysql:5.6
    restart: "no"
    volumes:
      - /home/joffroy/vhost/j4dev/ASGLM_Test/db:/var/lib/mysql:rw
    networks:
      - data
    ports:
      - 13307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - joomladb
    ports:
      - "91:80"
    environment:
      PMA_HOST: joomladb
    networks:
      - data
